name: build

env:
  PROJECT: 'Favor'
  # app archive 및 export 에 쓰일 환경 변수 설정
  XC_PROJECT: ${{ 'Favor/Favor.xcodeproj' }}
  XC_SCHEME: ${{ 'Favor' }}
  XC_ARCHIVE: ${{ 'Favor.xcarchive' }}
  XC_IPA: ${{ 'Favor.ipa' }}

  KEYCHAIN: ${{ 'build.keychain' }}

on:
  pull_request:
    branches: [ main, dev ]
  merge_group:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create secret file
      env:
        API_SECRET: ${{ secrets.API_SECRET }}
        TERM_SECRET: ${{ secrets.TERM_SECRET }}
        AUTHKEY_SECRET: ${{ secrets.APPSTORE_AUTHKEY }}
        KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
      run: |
        echo $API_SECRET | base64 -D -o ${{ env.PROJECT }}/${{ env.PROJECT }}NetworkKit/Sources/${{ env.PROJECT }}NetworkKit/API-Info.plist
        echo $TERM_SECRET | base64 -D -o ${{ env.PROJECT }}/${{ env.PROJECT }}/Term-Info.plist

    - name: Setup Xcode
      if: ${{ !env.ACT }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'
  
    - name: Build
      env:
        XCODEPROJ: "${{ env.PROJECT }}/${{ env.PROJECT }}.xcodeproj"
      run: >
        xcodebuild build
        -project ${{ env.XCODEPROJ }}
        -scheme ${{ env.XC_SCHEME }} 
        -sdk 'iphonesimulator' \
        -destination 'platform=iOS Simulator,OS=17.0.1,name=iPhone 15 Pro' \
